export const libft = [
  {
    title: "Standard",
    functions: [
      "memset",
      "bzero",
      "memcpy",
      "memccpy",
      "memmove",
      "memchr",
      "memcmp",
      "strlen",
      "strdup",
      "strcpy",
      "strncpy",
      "strcat",
      "strncat",
      "strlcat",
      "strchr",
      "strrchr",
      "strstr",
      "strcmp",
      "strncmp",
      "atoi",
      "isalpha",
      "isdigit",
      "isalnum",
      "isascii",
      "isparint",
      "toupper",
      "tolower",
    ],
  },
  {
    title: "Additional",
    functions: [
      "ft_memalloc",
      "ft_memdel",
      "ft_strnew",
      "ft_strdel",
      "ft_strclr",
      "ft_striter",
      "ft_striteri",
      "ft_strmap",
      "ft_strmapi",
      "ft_strequ",
      "ft_strnequ",
      "ft_strsub",
      "ft_strjoin",
      "ft_strtrim",
      "ft_strsplit",
      "ft_itoa",
      "ft_putchar",
      "ft_putstr",
      "ft_putendl",
      "ft_putnbr",
      "ft_putchar_fd",
      "ft_putstr_fd",
      "ft_putendl_fd",
      "ft_putnbr_fd",
    ],
  },
  {
    title: "Bonus",
    functions: [
      "ft_lstnew",
      "ft_lstdelone",
      "ft_lstdel",
      "ft_lstadd",
      "ft_lstiter",
      "ft_lstmap",
    ],
  },
  {
    title: "Personal",
    functions: [
      "get_next_line",
      "get_next_line_link",
      "ft_printf",
      "ft_absolute",
    ],
  },
];
